ccflags-y                       += -I$(srctree)/drivers/parrot
ccflags-$(CONFIG_UIO_HX_DEBUG)  += -DDEBUG

obj-$(CONFIG_UIO_HX) += hx-uio.o
obj-$(CONFIG_UIO_HX270) += hx270-vdec.o
obj-$(CONFIG_UIO_HX280) += hx280-venc.o
