#add parrot drivers here
obj-y += pwm/
obj-y += serial/
obj-y += block/
obj-y += usb/serial/blackberry/
obj-y += i2c/
obj-y += video/
obj-y += media/
obj-y += uio/
obj-y += gpu/
#obj-y += dma/
obj-y += net/
obj-y += mmc/
obj-y += regulator/
obj-y += spi/
obj-y += gpio/
obj-y += sound/p7_aai/
obj-y += mfd/
obj-y += rtc/
obj-y += pwm/
obj-y += pinctrl/
obj-y += input/
obj-y += gator/
obj-y += iio/
obj-y += clk/
obj-y += crypto/
obj-y += power/
obj-y += lttng/
obj-y += cpufreq/
# Without this, built-in.o won't be created when it's empty, and the
# final vmlinux link will fail.
obj-y += dummy.o
