#
# Makefile for industrial I/O pressure drivers
#

ccflags-y += -I$(srctree)/drivers/parrot

# When adding new entries keep the list in alphabetical order
obj-$(CONFIG_PARROT_IIO_MYKONOS3) += mykonos3.o
