obj-$(CONFIG_COMMON_CLK)      += clock.o
obj-$(CONFIG_COMMON_CLK)      += clk-pll.o
obj-$(CONFIG_COMMON_CLK)      += clk-avipll.o
obj-$(CONFIG_COMMON_CLK)      += clk-gbc.o
obj-$(CONFIG_COMMON_CLK)      += clk-xin.o
obj-$(CONFIG_COMMON_CLK)      += clk-sd.o
