
p7-i2cm-core-objs := p7-i2cm_legacy.o
obj-$(CONFIG_I2CM_PARROT7)          += p7-i2cm-core.o
obj-$(CONFIG_I2CM_PARROT7_DEBUGFS)  += p7-i2cm_debugfs.o
obj-$(CONFIG_PLDS_I2CS)             += plds_i2cs.o
obj-$(CONFIG_PARROT_SMSC_USB82514_USB_HUB) += smsc-82514-usb-hub.o
obj-$(CONFIG_TI_UB925_LVDS)         += ti_ub925_lvds.o

obj-y                               += muxes/
