#
# Makefile for industrial I/O pressure drivers
#

ccflags-y += -I$(srctree)/drivers/parrot

# When adding new entries keep the list in alphabetical order
obj-$(CONFIG_PARROT_IIO_MS5607) += ms5607.o
