
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := ethtool
LOCAL_DESCRIPTION := Display or change Ethernet card settings
LOCAL_CATEGORY_PATH := network

LOCAL_AUTOTOOLS_VERSION := 3.4.2
LOCAL_AUTOTOOLS_ARCHIVE := $(LOCAL_MODULE)-$(LOCAL_AUTOTOOLS_VERSION).tar.gz
LOCAL_AUTOTOOLS_SUBDIR := $(LOCAL_MODULE)-$(LOCAL_AUTOTOOLS_VERSION)

include $(BUILD_AUTOTOOLS)

