ccflags-$(CONFIG_MFD_P7MU_DEBUG)    += -DDEBUG
obj-$(CONFIG_MFD_P7MU)              += p7mu-core.o p7mu-clk.o p7mu-pin.o
obj-$(CONFIG_MFD_DIB0700)	    += dib0700_mfd.o
obj-$(CONFIG_SICILIA_IRRADIANCE)    += sicilia-irradiance.o
