# Parrot Platform Support
# Use a dummy platform. The Alsa standard AAI driver is used

# Parrot Machine Support
snd-soc-parrot-fc7100-objs := parrot-fc7100.o

obj-$(CONFIG_SND_SOC_PARROT_FC7100) += snd-soc-parrot-fc7100.o

